load_paths:
  - lib/assets/javascripts/src
  - test/javascripts/src
  - test/javascripts/vendor
  - test/javascripts/fixtures

logical_paths:
  - local-time.js
  - test.js

build:
  logical_paths:
    - local-time.js
  path: app/assets/javascripts
  js_compressor: uglifier

require:
  - sprockets/export

plugins:
  sauce_labs:
    test_config:
      time_zone: Central
      max_duration: 300
    browsers:
      Google Chrome:
        version: -2
        os: Mac, Windows, Linux
      Firefox:
        version: -2
        os: Mac, Windows, Linux
      Safari:
        version: -2
      Microsoft Edge:
        version: -2
      Internet Explorer:
        version: -3
      iPhone:
        version: -2
      Android:
        version: -2
